task-1/frameworks
MChornomaz/Node.js_Course_Practice pull request #1
Opened 2023-10-03 16:46 UTC by MChornomaz

HW-1 asynchronous-environment

![image](https://github.com/MChornomaz/Node.js_Course_Practice/assets/68593365/a930929f-d829-4a50-bdb1-3ee16cf0d307)

2023-10-04 12:56 UTC, KryvDanylo requested changes

2023-10-04 12:56 UTC, KryvDanylo commented on index.js
Move this file to src, it's also part of the app code.

2023-10-04 12:56 UTC, KryvDanylo commented on src/models/http-error.js
It's very good to create custom errors, so I propose moving it to the errors folder it would be more logical for the architecture of app.

2023-10-04 12:56 UTC, KryvDanylo commented on src/constants/API-paths.js
You can set prefix /api for all of the routes using app.use("/api", mainRoute);

2023-10-04 12:56 UTC, KryvDanylo commented on index.js
> +app.use(healthCheckRoute)
You can create an index file in the routes folder for the main route and use it with the prefix /api

2023-10-04 15:46 UTC, KryvDanylo requested changes

2023-10-04 15:46 UTC, KryvDanylo commented on index.js
> +
Also I didn't see error handler

2023-10-04 18:32 UTC, MChornomaz commented on src/models/http-error.js
@KryvDanylo  src/models/errors or src/errors?

2023-10-05 15:09 UTC, KryvDanylo requested changes

2023-10-05 15:09 UTC, KryvDanylo commented on src/index.js
> +app.use((err, req, res, next) => {
Please create a folder for middleware and move it there.

2023-10-06 10:46 UTC, KryvDanylo approved these changes
Very good!

2023-10-07 19:36 UTC, merged